language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FkR0SsIVc2WVjcAdKKHGMy3Ry/izLcDEREOyiXD4EIREym3w/6aTJ1YzD8cMRwdvYy4tvy03eyUdnAucx2JQQZjpZGiWyQfo/6hExtaK2AjtUuepIR4LAPlgZ2RU9S3bOi4R/SYaFy/qzzfg1NEx0K5L5GNqIzj1YlYZgu9d6xgDzmHe38aMMU/92yxjTJ3XGH0ku56cWqQOYYqQYgs+k+mM+Eg9dDwOZaZXonEfK8p68TRm1lM2LO1OFeszSg8o6i41xp1UW/O6uag5SZT45Z+6zIpZI1kOKu66Tklg+C8M+fX5X9mPaKlYOIjeXyRoit/r7czWlB3PCkx1p+ES+gkjpF5EULIJDIp17HcQJUT6J0smB6OyWlG3VavotnJX7sVAvkZRTUqrWY62HvK+yvEkvKDAhx07n+wFUdrlOzqrMuWf88cKE/DMJwkym802rsKDRxMfnkT89I4fJoJGbUN6U9XpHgAeocOPV05XWmsX09w/qR4oAf2AM4bf6RXaDYduh8UuFQo/eLxbI79NFj091lVS7DSJzjlonXjM1+ghj2VaFNFD0pc9HtQhdQHYJeH3Tf6gVnYA3BwR9OjTSIY28rinove9AKF8SpBcX8eSKHneaFIDNY29MT4jnPYYOYCmCUbpGXY4TGlwugZaw/SoXyuObuIvhZdlKIvj+yQ=
  file:
    - 'unist-util-find-before.js'
    - 'unist-util-find-before.min.js'
  on:
    tags: true
